name-template: "E2E $RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
change-template: "- $TITLE (#$NUMBER)"
category-template: "### $TITLE"
template: |
  # Changelog

  ## v$RESOLVED_VERSION

  $CHANGES
categories:
  - title: Features
    semver-increment: minor
    when:
      label: feature
  - title: Fixes
    semver-increment: patch
    when:
      label: bug
  - title: Other changes
