name-template: "E2E $RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
change-template: "- $TITLE (#$NUMBER)"
category-template: "### $TITLE"
template: "\n\n## v$RESOLVED_VERSION\n\n$CHANGES\n\n"
categories:
  - title: Features
    semver-increment: minor
    when:
      label: feature
  - title: Fixes
    semver-increment: patch
    when:
      label: bug
  - title: Other changes

